cloudocs/config/routes.rb
Cloudocs::Application.routes.draw do
  root to: "top#index"
  get "editor/" => "editor#index"
  get "editor/index"
  get "editor/new"
  get "editor/login"
  get "editor/sign_up"
  get "editor/edit/:id" => "editor#edit"
  post "editor/create"
  post "editor/save/:id" => "editor#save"
  post "api/get_file" => "api#get_file"
  get "api/payload"
  post "api/payload" => "api#payload"
  resource :session
  resource :users

end

cloudocs/app/models/.#user.rb
yoshiro@yoshiro-VirtualBox.2984:1403239388

cloudocs/app/models/file_stat.rb
class FileStat < ActiveRecord::Base
  validates :name, :uniqueness => true
  validates :name, :format => {with: /\A[^\/\0]+\Z/} # ファイル名に"/","\0"は使用禁止
end

cloudocs/app/models/locking.rb
class Locking < ActiveRecord::Base
end

cloudocs/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :name, presence: true, uniqueness: true
  validates :password_digest, presence: true      
end

cloudocs/app/controllers/api_controller.rb
require 'json'

class ApiController < ActionController::Base
  # handling webhook
  def payload
    if request.post? #### POST REQUEST
      # get secret from environment variables
      secret = ENV['SECRET_TOKEN']
      # verify signature
      if verify_signature(request.body.read, secret) == 500 
        render :text => "invalid signature", :status => 403
        return 
      end
      # parse payload
      push = request.body.read ? JSON.parse(request.body.read) : nil
 
      # validate json parameters
      if !defined?(push["ref"])
        render :text => "ref is not set", :status => 403
        return 
      end
      if !defined?(push["pusher"])
        render :text => "pusher is not set", :status => 403
        return
      end
      if !defined?(push["repository"]) || !defined?(push["repository"]["url"]) || push["repository"]["url"] != "https://github.com/amiq11/cloud2014-C1"
        render :text => "repository is not set, or invalid repository url", :status => 403
        return 
      end
      # ignore push notification not by master branch
      if push["ref"] != "refs/heads/master"
        render :text => "ignored because not pushed into master branch", :status => 200
        return 
      end
      # pull 
      result = system("git pull")
      if result
        r = system("touch tmp/restart.txt")
        txt = (r) ? "SUCCEEDED" : "FAILED"
        render :text => "DEPLOY SUCCEEDED and SERVER RESTART #{txt}", :status => 200
      else
        render :text => "INTERNAL SERVER ERROR (DEPLOY FAILED)", :status => 500
      end
      return 
    else 
      render :text => "GET REQUEST IS NOT ALLOWED", :status => 403
    end
  end


  def get_file
    if request.post? #### POST REQUEST
	  puts request
      #req = request.body.read ? JSON.parse(request.body.read) : nil
	  updated_file = FileStat.find(request['id'])
	  render :json => {'body' => File.open(updated_file.path, "r").read}
	end
  end





  private 
  def verify_signature(payload_body, secret)
    signature = 'sha1=' + OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), secret, payload_body)
    return 500 unless Rack::Utils.secure_compare(signature, request.env['HTTP_X_HUB_SIGNATURE'])
  end
  
  protect_from_forgery with: :null_session
end

cloudocs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :current_user, :login_required
  
  def current_user
    if session[:user_id]
      # @current_userがnilかfalseならログインユーザーを代入
      @current_user ||= User.find(session[:user_id])
    end
  end

  def login_required
    redirect_to session_path unless @current_user
  end
      

  helper_method :current_user

end

cloudocs/app/controllers/doc_controller.rb
class DocController < ApplicationController
  def index
  end

  def login
  end

  def sign_up
  end

  def create
  end

  def edit
  end
end

cloudocs/app/controllers/editor_controller.rb
class EditorController < ApplicationController
  protect_from_forgery :except => [:save]
  Save_dir = "/mnt/cloudocs-volume/documents/"

  def index
    @file_stats = FileStat.find(:all)
  end

  def new
    @file_stat = FileStat.new
  end

  def sign_up
  end
  
  def edit
  	@file = FileStat.find(params[:id])
  end
  
  def save
  	return redirect_to '/404.html' unless request.xhr?
  	@file = FileStat.find(params[:id])
  	if params[:body]
  		File.open(@file.path, "w") do |file|
  			file.write params[:body]
  		end
  	end
  end

  def create
    attr = params.require(:file_stat).permit(:name)
    @file_stat = FileStat.create(attr)
    @file_stat.path = Save_dir + @file_stat.name
    if @file_stat.save
      begin
        f = open(Save_dir + @file_stat.name, "w")
        f.close
        redirect_to editor_index_path
      rescue
        FileStat.find(:last, :conditions => {:name => @file_stat.name}).destroy
        flash[:notice] = "Failed to create new file entity."
        redirect_to :action => "new"
      end
    else
      case @file_stat.errors.messages.fetch(:name)[0]
      when "has already been taken"
        flash[:notice] = "\"" + @file_stat.name + "\" " + "is already exists." 
      when "is invalid"
        flash[:notice] = "File name must not contain \"\/\"." 
      else
        flash[:notice] = "Failed to create new file stat."
      end
      redirect_to :action => "new"
    end
  end
end

cloudocs/app/controllers/sessions_controller.rb
# -*- coding: utf-8 -*-
class SessionsController < ApplicationController
skip_before_filter :login_required
  def show
    render "new"
  end

  def create
	user = User.find_by_name params[:name]
	if user && user.authenticate(params[:password])
		session[:user_id] = user.id
		redirect_to :controller => 'editor', :action => 'index'
	else
      		flash.now.alert = "もう一度やり直してんなー"
      		render "new"
    	end

  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_path

  end

end

cloudocs/app/controllers/top_controller.rb
class TopController < ApplicationController
skip_before_filter :login_required
 def index
   if @current_user 
     redirect_to :controller => "editor", :action => "index"
   end
 end
end

cloudocs/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_filter :login_required
    def new  
	@user = User.new  
    end  
  
    def create  
    	attr = params.require(:user).permit(:name, :email, :password, :password_confirmation)
	@user = User.create(attr)
    	if @user.save  
      		redirect_to root_path, :notice => "Signed up!"  
    	else  
      		render "new"  
    	end  
    end  
	
end

cloudocs/app/helpers/api_helper.rb
module ApiHelper
end

cloudocs/app/helpers/application_helper.rb
module ApplicationHelper
end

cloudocs/app/helpers/doc_helper.rb
module DocHelper
end

cloudocs/app/helpers/editor_helper.rb
module EditorHelper
end

cloudocs/app/helpers/sessions_helper.rb
module SessionsHelper
end

cloudocs/app/helpers/top_helper.rb
module TopHelper
end

cloudocs/app/helpers/users_helper.rb
module UsersHelper
end

cloudocs/app/views/editor/edit.html.erb
<%= stylesheet_link_tag "edit_style" %>
<h1><%= @file.name -%></h1>
<div id="post_status" style="height: 20px; display:block;">   </div>

<div id="description">
	<p>※ vim キーバインドです！<S>emacs?何それおいしいの?</S></p>
	<p>Macなら<strong>Command-s</strong>, Windowsなら<strong>Ctrl-s</strong>で保存</p>
</div>
<%= link_to "一覧に戻る", :action => "index" -%>

<% if File.readable? @file.path %>
	<div id="editor-div"><%= File.open(@file.path, "r").read -%></div>

	<% @ext = @file.name.split(".")[-1] %>

<% else %>
	<p>This is not file!</p>
<% end %>


<%= javascript_tag do%>
	var editor = ace.edit("editor-div");
	window.onload = function() {
		editor.setTheme("ace/theme/twilight");
		editor.setKeyboardHandler("ace/keyboard/vim");
		editor.getSession().setMode("ace/mode/<%= @ext %>");
		editor.focus();

		editor.commands.addCommand({
			Name: "savefile",
			bindKey: {
				win: "Ctrl-S",
				mac: "Command-S"
			},
			exec: function(editor) {
				$.ajax({
					url: '/editor/save/<%= @file.id.to_s -%>',
					type: 'post',
					data: {body: editor.getSession().getValue()},
					success: function() {
						$("#post_status").css("display", "block");
						$("#post_status").css("height", "20px");
						$("#post_status").html("保存しました").fadeOut("2000000").queue(function() {
							$("#post_status").css("display", "block").dequeue();
							$("#post_status").html("		").dequeue();
							});
						$("#post_status").css("height", "20px");
					}
				});
			}
		});
	};

<% end %>

cloudocs/app/views/editor/index.html.erb
<h1>Editor#index</h1>
<p>Find me in app/views/editor/index.html.erb</p>
<table border="0">
  <tr>
  </tr>
<% @file_stats.each do |file| %>
  <tr>
    <td><%= file.id %></td>
    <td><%= file.name %></td>
    <td><%= file.path %></td>
    <td><%= file.user_id %></td>
    <td><%= link_to "edit" , :action=>"edit" , :id=> file.id =%></td>
  </tr>
<% end %>
</table>
<br>
<br>
<b><%= link_to "CREATE" , :action=>"new" =%></b>
<br>
<br>
<b><%= link_to "LOG OUT" , session_path,  :confirm=>"LOG OUT OK?" , :method=>:delete =%></b>

cloudocs/app/views/editor/login.html.erb
<h1>Editor#login</h1>
<p>Find me in app/views/editor/login.html.erb</p>

cloudocs/app/views/editor/new.html.erb
<h1>Create new file</h1>

<p> <%= flash[:notice] %> </p>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @file_stat, :url => {:action => 'create'} do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create!!!!!", class: "btn" %>
    <% end %>
  </div>
</div>
<p><%= link_to "Back", editor_path %></p>

cloudocs/app/views/editor/sign_up.html.erb
<h1>Editor#sign_up</h1>
<p>Find me in app/views/editor/sign_up.html.erb</p>

cloudocs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloudocs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

cloudocs/app/views/shared/_errors.html.erb
<% unless obj.errors.empty? %>
<div id="errors">
<h2>エラーがあります。</h2>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

cloudocs/app/views/top/index.html.erb
<h1>トップページ</h1>
<p>コニチワ</p>

<% if current_user == nil %>
  <%= link_to "ログインするのです！！", session_path, :confirm => 'これはゲームであっても遊びではない' %><br>
  <%= link_to "新しく作るのん", new_users_path %><br>
<% else %>
  <%= link_to 'ログアウト', session_path, :confirm => 'ログアウトできます', :method => :delete %>
<% end %>

cloudocs/app/views/users/new.html.erb
<h1>Sign Up</h1>  
<%= render "shared/errors", obj: @user %>

<%= form_for @user do |f| %>  
  <div class="field">  
    <%= f.label :name %>  
    <%= f.text_field :name %>  
  </div>
  <div class="field">  
    <%= f.label :email %>  
    <%= f.text_field :email %>  
  </div>   
  <div class="field">  
    <%= f.label :password %>  
    <%= f.password_field :password %>  
  </div>  
  <div class="field">  
    <%= f.label :password_confirmation %>  
    <%= f.password_field :password_confirmation %>  
  </div>  
  <div class="actions"><%= f.submit %></div>  
<% end %>